plugins: 
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}

static_map: 
    map_topic: map
obstacles:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: base_link , data_type: LaserScan, topic: scan_wcr_averaged, marking: true, clearing: true}
    track_unknown_space: true
    obstacle_range: 2.5
    raytrace_range: 3.0

footprint: [[-0.52, -0.37], [-0.52, 0.37], [0.52, 0.37], [0.52, -0.37]]
#robot_radius: 0.17

inflation_radius: 0.0
cost_scaling_factor: 3.0

global_frame: map
robot_base_frame: base_link
update_frequency: 20.0
publish_frequency: 10.0
transform_tolerance: 0.5