plugins: 
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}

static_map: 
    map_topic: unoccupied_map
obstacles:
    observation_sources: laser_scan_sensor_front laser_scan_sensor_back
    laser_scan_sensor_front: {sensor_frame: laser_frame_front , data_type: LaserScan, topic: front_scan, marking: true, clearing: false, inf_is_valid: false}
    laser_scan_sensor_back: {sensor_frame: laser_frame_back , data_type: LaserScan, topic: back_scan, marking: true, clearing: false, inf_is_valid: false}
    track_unknown_space: true
    obstacle_range: 4.0
    raytrace_range: 1.5

footprint: [[-0.52, -0.37], [-0.52, 0.37], [0.52, 0.37], [0.52, -0.37]]
#robot_radius: 0.17

inflation_radius: 0.0
cost_scaling_factor: 3.0

global_frame: map
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 3.0
transform_tolerance: 0.15